name: NameManager
main: net.agentlv.namemanager.NameManager
version: ${version}
author: AgentLV
softdepend: [Vault]
api-version: 1.19

commands:
  namemanager:
    aliases: nm
    usage: /namemanager
    description: Displays the author and the version of the plugin.