# Should NameManager handle join and leave messages?
# For more information visit: http://www.spigotmc.org/resources/namemanager.5147/
Messages: false
CustomNameForMessages: false
Join: '&a[+] %player%'
Leave: '&c[-] %player%'
HealthBelowName: false
HealthFormat: '&c❤'