# For more information and details visit: http://www.spigotmc.org/resources/namemanager.5147/

Messages: false
CustomNameForMessages: false
Join: '&a[+] %player%'
Leave: '&c[-] %player%'
HealthBelowName: false
HealthFormat: '&c❤'
Bungee: false