# Should NameManager handle join and leave messages?
Messages: false

# Should NameManager include the prefixes and suffixes in the join & leave messages?
CustomNameForMessages: false
Join: '&a[+] %player%'
Leave: '&c[-] %player%'

# Should NameManager display the health of a player below their name?
HealthBelowName: false
HealthFormat: '&c❤'

# Don't touch this!
version: 1.1