# Should NameManager handle join and leave messages?
Messages: false

# Should NameManager include the prefixes and suffixes in the join & leave messages?
CustomNameForMessages: false
Join: '&a[+] %player%'
Leave: '&c[-] %player%'

# Don't touch this!
version: 1.0