name: NameManager
main: io.github.AgentLV.NameManager
version: 1.7.2
author: AgentLV
commands:
  namemanager:
    aliases: nm
    usage: /namemanager
    description: Shows the author and the version of the plugin.
  namemanager help:
    usage: /namemanager
    description: Lists the commands.
  namemanager prefix:
    usage: /namemanager prefix <player> <name>
    description: Sets the prefix of a player.
  namemanager suffix:
    usage: /namemanager suffix <player> <name>
    description: Sets the suffix of a player.
  namemanager clear:
    usage: /namemanager clear <player>
    description: Clears the name of a player.
  namemanager uuid:
    usage: /namemanager uuid <player>
    description: Gets the UUID of a player.
  namemanager rainbow:
    usage: /namemanager rainbow [player]
    description: Turns your name into a rainbow.

permissions:
  NameManager.help:
    description: Allows the usage of /nm help.
  NameManager.prefix:
    description: Allows the usage of /nm prefix.
  NameManager.suffix:
    description: Allows the usage of /nm suffix.
  NameManager.clear:
    description: Allows the usage of /nm clear.
  NameManager.uuid:
    description: Allows the usage of /nm uuid.
  NameManager.rainbow:
    description: Allows the usage of /nm rainbow.
  NameManager.black:
    description: Changes the displayname to black.
  NameManager.darkblue:
    description: Changes the displayname to darkblue.
  NameManager.darkgreen:
    description: Changes the displayname to darkgreen.
  NameManager.darkaqua:
    description: Changes the displayname to darkaqua.
  NameManager.darkred:
    description: Changes the displayname to darkred.
  NameManager.darkpurple:
    description: Changes the displayname to darkpurple.
  NameManager.gold:
    description: Changes the displayname to gold.
  NameManager.gray:
    description: Changes the displayname to gray.
  NameManager.darkgray:
    description: Changes the displayname to darkgray.
  NameManager.blue:
    description: Changes the displayname to blue.
  NameManager.green:
    description: Changes the displayname to green.
  NameManager.aqua:
    description: Changes the displayname to aqua.
  NameManager.red:
    description: Changes the displayname to red.
  NameManager.lightpurple:
    description: Changes the displayname to lightpurple.
  NameManager.yellow:
    description: Changes the displayname to yellow.
  NameManager.white:
    description: Changes the displayname to white.    