name: NameManager
main: de.agentlv.namemanager.NameManager
version: 2.0
author: AgentLV
softdepend: [Vault]

commands:
  namemanager:
    aliases: nm
    usage: /namemanager
    description: Displays the author and the version of the plugin.
